parameters:
#    rob_masters_task.example.class: RobMasters\Bundle\TaskBundle\Example

services:
#    rob_masters_task.example:
#        class: %rob_masters_task.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
